sphere_points_count : 32
current_sphere_radius : 2
sphere_expansion_coeff : 1.3
step_size : 0
current_iter : 0
point_clamp_min : -1.5
point_clamp_max : 1.5
max_iters_at_radius_before_terminate : 1000
z_dim : 100
num_targets : 300
batch_dim_for_initial_points : 256
repulsion_only : True
targeted_attack: False
